### ISSUE TITLE
iOS arm64 bit support

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#2685]
Add support for the 64 bit arm architecture:
- [ ] update ios cmake toolchain file (#2162) 
  - [ ] add arm64 support
  - [ ] add support for 64 bit simulator (x86_64)
- [x] update openssl build script (#2651, #2680) - fixed with PR #2686
- [ ] update and test code/types for 64 bit arm (#2162)

**Comment by wangfuda** [comment]
why the version of ifreeRDP(iOS) in offical web site (http://www.freerdp.com/) can run normal in arm64 such as iphone 5s, iphone 6p?

**Comment by bmiklautz** [comment]
@wangfuda what do you exactly mean? As far as I know there wasn't any official release (play store and app store) that supported 64 bit.

**Comment by wangfuda** [comment]
@bmiklautz  this version from app store(https://itunes.apple.com/us/app/ifreerdp/id604813768) can run normal in iphone5s,iphone

**Comment by bmiklautz** [comment]
@wangfuda that's right but it's not compiled/published as a 64 bit application. As far as I'm aware of old apps could be published without 64 support.

**Comment by wangfuda** [comment]
@bmiklautz thanks for your help. hope the 2.0 come soon.：）

**Comment by VinodJagtap** [comment]
Is their any upgradation for arm64 bit support?

**Comment by bmiklautz** [comment]
@VinodJagtap @akallabeth has recently done some improvements and updates for the Android build system. arm64 requires openssl 1.1.x  (openssl 1.0.x doesn't officially support arm64) but FreeRDP does only support openssl < 1.1 at the moment.
So it basically should work but you need a "patched" version of openssl 1.0.x.
 @akallabeth correct me if I'm wrong.
