### ISSUE TITLE
Implement missing features for wayland client

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#5076]
The wayland client is currently a very poor proof of concept.
Any help to improve the current situation is welcome.

If you're interested the following features and fix existing issues are currently unsolved:
- [x] Mouse cursor support #3415
- [x] Display resizing support via display channel #5159
- [x] Window decorations #5165
  - [ ] Fallback to client side decorations
- [x] Clipboard support #3414 #5160 
  - [ ] Additional clipboard formats #5220 
- [x] Keyboard grab #4799
- [x] Fullscreen shell #5162 
- [ ] Multimonitor #5163
- [x] Fix drawing issues #5161
- [ ] RAIL support #5164
- [x] Window fixed size vs resizable support #5215

**Comment by eMPee584** [comment]
\+
* [ ] window rotation support
* [ ] :smiley:

**Comment by akallabeth** [comment]
@eMPee584 hmm, nice idea. #5159 should already implement the client server communication part, so it should be a simple matter of reading the current state in case of configure

**Comment by pnowack** [comment]
> Fallback to client side decorations

For client side decorations, `libdecor` can be used (current upstream repo is at https://gitlab.gnome.org/jadahl/libdecor (in the future maybe on freedesktops gitlab (https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/420))).
It is packaged in current distros (F34+, Archlinux, ...)

**Comment by akallabeth** [comment]
wayland client will be deprecated and replaced with sdl-client.
