### ISSUE TITLE
TODO: smartcard related items

### ISSUE THREAD

**Issue by hardening** [FreeRDP/FreeRDP#7707]
NLA smartcard  logon PR has been merged, anyway I'm seeing items that still need work:

* [x] make smartcard emulation a runtime option and not a build option, so that we can choose at runtime if we have real smartcard or the emulation (that a matter of having a struct with all smartcard functions that we would fill with the correct functions);
* [x] implement container name computation under linux and Mac so that NLA smartcard logon works from scratch without having to specify by hand the correct containerName (retrieved by connecting the card under windows). The algorithm involves retrieving the guid of the card for PIV cards (and pick the container id of the cert), and for GIDS cards it's another algorithm (EFS.dir I think)
* [x] make TLS smartcard logon more convenient, like if there's only one smartcard with one certificate, then automatically pick the user and domain from the smartcard

**Comment by akallabeth** [comment]
@hardening Just a note: last option (TLS) already works, that is how we do logon here.
Do I miss something here or is it maybe dependent on device in use?

**Comment by hardening** [comment]
Here if I just run `xfreerdp /v:<target> /sec:tls /smartcard-logon:pin:<pin>` with just one smartcard plugged in a user and a domain are asked, while we could guess them.

**Comment by akallabeth** [comment]
@hardening we use `xfreerdp /v:<target> /sec:tls /smartcard-logon /p:<pin> +password-is-pin` as without the last setting the `info` packet does not send the correct flags.

**Comment by akallabeth** [comment]
@hardening I´d add another item for:
* `CredMarshalCredential` implementation in `WinPR` so we don´t need the `#ifdef _WIN32` switches in `nla.c`
* Switch all functions in `nla.c` to the `*W` (unicode) versions as we don´t want to limit usernames/passwords to `ANSI`

**Comment by hardening** [comment]
There's a fundamental limitation with using `CredMarshalCredential`: with an existing kerberos cache I'm not sure we can ensure that this cache has been established with pkinit by a given certificate (given by SHA1). `CredMarshalCredential` is so much a system oriented things with lots of implicits under windows. 
I was thinking that when it's FreeRDP that is initiating the cache, we could also create a meta data file (cache: /tmp/krb5cc_1000 meta: /tmp/krb5cc_1000.meta) and put the pkinit parameters in it (like slotId and certId) so that we can retrieve them with an emulated `CredMarshalCredential` call in winPR. That would do the trick when it's a cache initiated by FreeRDP but not when you establish your kerberos cache by hand.
If you have a better idea...

**Comment by akallabeth** [comment]
@hardening just wanted to add the remaining `TODO` items, I´m currently also out of ideas (e.g. must read into the issue first)

**Comment by hardening** [comment]
Only smartcard emu as runtime thing and we're done !

**Comment by akallabeth** [comment]
@hardening I think this is already done, is it not?
